# Generated by Django 4.2.2 on 2023-06-28 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_book_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBookRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False, verbose_name='Like')),
                ('in_bookmarks', models.BooleanField(default=False, verbose_name='In bookmarks')),
                ('rate', models.PositiveSmallIntegerField(choices=[(1, 'Bad'), (2, 'Ok'), (3, 'Good'), (4, 'Amazing'), (5, 'Incredible')], verbose_name='Rate')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.book', verbose_name='Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
    ]
