# Generated by Django 4.2.2 on 2023-06-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_book_readers_alter_book_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrelation',
            name='in_bookmarks',
            field=models.BooleanField(default=False, null=True, verbose_name='In bookmarks'),
        ),
        migrations.AlterField(
            model_name='userbookrelation',
            name='like',
            field=models.BooleanField(default=False, null=True, verbose_name='Like'),
        ),
        migrations.AlterField(
            model_name='userbookrelation',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Bad'), (2, 'Ok'), (3, 'Good'), (4, 'Amazing'), (5, 'Incredible')], null=True, verbose_name='Rate'),
        ),
    ]
