# Generated by Django 4.2.2 on 2023-06-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_userbookrelation_in_bookmarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrelation',
            name='in_bookmarks',
            field=models.BooleanField(default=False, verbose_name='In bookmarks'),
        ),
        migrations.AlterField(
            model_name='userbookrelation',
            name='like',
            field=models.BooleanField(default=False, verbose_name='Like'),
        ),
    ]
