# Generated by Django 4.2.2 on 2023-06-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_userbookrelation_in_bookmarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookrelation',
            name='review',
            field=models.TextField(null=True, verbose_name='Review'),
        ),
    ]
