# Generated by Django 4.2.2 on 2023-06-29 12:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_userbookrelation_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=3, verbose_name='Discount'),
        ),
    ]
