# Generated by Django 4.2.2 on 2023-06-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_book_rating_alter_userbookrelation_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3, verbose_name='Rating'),
        ),
    ]
