# Generated by Django 4.2.2 on 2023-06-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_book_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrelation',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Bad'), (2, 'Ok'), (3, 'Good'), (4, 'Amazing'), (5, 'Incredible')], null=True, verbose_name='Rate'),
        ),
    ]
